### ISSUE TITLE
Running it on docker without the install-Container - Does not Start / "We could not connect to your broker"

### ISSUE THREAD

**Issue by XRyu** [cedalo/management-center#16]
I have the MMC running in Docker on my Synology 918+, connected to my Broker (which was there long before ;) but updated to 2 yesterday) by setting the Environment-Variables. This is how my compose looks like:

```
  mqtt-mmc:
    container_name: mosquitto-mmc
    restart: unless-stopped
    image: cedalo/management-center:dev
    environment:
      TZ: Europe/Berlin
      PGID: 100
      PUID: 1026
      CEDALO_MC_BROKER_ID: mosquitto-2.0
      CEDALO_MC_BROKER_NAME: TortugaMQTT
      CEDALO_MC_BROKER_URL: mqtt://192.168.178.101:1883
      CEDALO_MC_BROKER_USERNAME: 7his15N0Username12345
      CEDALO_MC_BROKER_PASSWORD: *aWeSomePasswordHere%
      CEDALO_MC_PROXY_CONFIG_DIR: /management-center/config/config.json
    volumes:
    - /etc/localtime:/etc/localtime
    - /etc/hosts:/etc/hosts
    - certs:/certs
    - /volume1/docker/mosquitto-mmc/config:/management-center/config
    ports:
    - "1888:8088/tcp"

  mqtt:
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto:2
    environment:
    - TZ=Europe/Berlin
    - PGID=100
    - PUID=1026
    volumes:
    - /etc/localtime:/etc/localtime
    - /etc/hosts:/etc/hosts
    - certs:/certs
    - /volume1/docker/mosquitto/config:/mosquitto/config
    - /volume1/docker/mosquitto/data:/mosquitto/data
    - /volume1/docker/mosquitto/log:/mosquitto/log
    ports:
    - "1883:1883/tcp"
    - "8083:8083/tcp"
    - "8883:8883/tcp"
    - "9001:9001/tcp"
    labels:
    - "com.centurylinklabs.watchtower.enable=false"

```

When i access it through my Browser i get:
![image](https://user-images.githubusercontent.com/131995/102213495-1b30b600-3ed7-11eb-9e2f-4f6bcf692a92.png)

And when i look at the logs:
![image](https://user-images.githubusercontent.com/131995/102213677-634fd880-3ed7-11eb-8bdf-169816bd3a72.png)

What am i missing? :)
BTW - Congratulations for the new Milestone :D

**Comment by cleancoderocker** [comment]
Maybe it helps if you create a Docker network. Should be something like this (notice the four new/changed sections).

```
  mqtt-mmc:
    container_name: mosquitto-mmc
    restart: unless-stopped
    image: cedalo/management-center:dev
    environment:
      TZ: Europe/Berlin
      PGID: 100
      PUID: 1026
      CEDALO_MC_BROKER_ID: mosquitto-2.0
      CEDALO_MC_BROKER_NAME: TortugaMQTT
      # 1. Change hostname here to point to the Docker network:
      CEDALO_MC_BROKER_URL: mqtt://mqtt-network:1883
      CEDALO_MC_BROKER_USERNAME: 7his15N0Username12345
      CEDALO_MC_BROKER_PASSWORD: *aWeSomePasswordHere%
      CEDALO_MC_PROXY_CONFIG_DIR: /management-center/config/config.json
    volumes:
    - /etc/localtime:/etc/localtime
    - /etc/hosts:/etc/hosts
    - certs:/certs
    - /volume1/docker/mosquitto-mmc/config:/management-center/config
    ports:
    - "1888:8088/tcp"
    # 2. Add this section:
    networks:
      - mqtt-network

  mqtt:
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto:2
    environment:
    - TZ=Europe/Berlin
    - PGID=100
    - PUID=1026
    volumes:
    - /etc/localtime:/etc/localtime
    - /etc/hosts:/etc/hosts
    - certs:/certs
    - /volume1/docker/mosquitto/config:/mosquitto/config
    - /volume1/docker/mosquitto/data:/mosquitto/data
    - /volume1/docker/mosquitto/log:/mosquitto/log
    ports:
    - "1883:1883/tcp"
    - "8083:8083/tcp"
    - "8883:8883/tcp"
    - "9001:9001/tcp"
    labels:
    - "com.centurylinklabs.watchtower.enable=false"
    # 3. Add this section:
    networks:
      - mqtt-network

# 4. Add this section here to configure the Docker network:
networks:
  mqtt-network:
    name: mqtt-network
    driver: bridge
```
