### ISSUE TITLE
Run Management Center with existing Mosquitto.

### ISSUE THREAD

**Issue by baardl** [cedalo/management-center#22]
Hi.

We have an existing mosquitto 2.0.7 running, without Docker. I would like to connect Management Center to that broker.
How can I do that?

Best regards
Bård Lind

**Comment by cleancoderocker** [comment]
Hi,

the easiest way is to use the installer [as described here](https://docs.cedalo.com/latest/docs/installation). During the installation you just unselect Mosquitto and only select the Management Center (optionally you can install Streamsheets as well if you want to give it a try).

After the installation you just need to change the following environment variables inside the Docker Compose file (and replace the placeholders below).

```
environment:
  CEDALO_MC_BROKER_ID: mosquitto-2.0
  CEDALO_MC_BROKER_NAME: Mosquitto 2.0
  CEDALO_MC_BROKER_URL: mqtt://<HOSTNAME_OR_IP_OF_BROKER>:1883
  CEDALO_MC_BROKER_USERNAME: <USERNAME>
  CEDALO_MC_BROKER_PASSWORD: <PASSWORD>
```
Let me know if that helped.

Best regards,
Philip

**Comment by baardl** [comment]
Thank you  for your quick reply.
When I try to deselect Mosquitto, Management Center is automatically deselected also.
Re-selecting MC, automatically re-select Mosquitto too. I guess I can solve that.
How can i make the MC docker listen to an external mosquitto, outside of Docker? I guess that is the real problem?

Best regards
Bård

**Comment by cleancoderocker** [comment]
Ah, you're right, the installer works that way :-) 

Accessing a host outside of Docker depends on your operating system and how you run Docker. For example under macOS you can use `docker.for.mac.localhost` and under Windows I think it's `docker.for.win.localhost` (at least when you use [Docker Desktop](https://www.docker.com/products/docker-desktop). So the URL for the environment variable `CEDALO_MC_BROKER_URL` would be `mqtt://docker.for.mac.localhost:1883`.

Best regards,
Philip

**Comment by baardl** [comment]
Hi Philip.

Here is the docker-compose.yml I used, and it is working fine. 
Now only ManagementCenter is running in Docker. 

```
version: "3.8"
services:
  management-center:
    image: cedalo/management-center:2
#    ports:
#      - 8088:8088
#      - 1883:1883
#    depends_on:
#      - mosquitto
    network_mode: "host"
    environment:
      CEDALO_MC_BROKER_ID: mosquitto-2.0
      CEDALO_MC_BROKER_NAME: Mosquitto 2.0
      CEDALO_MC_BROKER_URL: mqtt://localhost:1883
      CEDALO_MC_BROKER_USERNAME: <ourlocaladmin>
      CEDALO_MC_BROKER_PASSWORD: <ourlocaladmin>
      CEDALO_STREAMSHEETS_ID: streamsheets-local
      CEDALO_STREAMSHEETS_NAME: Streamsheets
      CEDALO_STREAMSHEETS_DESCRIPTION: Local Streamsheets
      CEDALO_STREAMSHEETS_URL: http://localhost:8081
volumes:
  streamsheets-data:
    external: true
networks:
  cedalo-platform:
    name: cedalo-platform
    driver: bridge
```

Feel free if you want to us it as an example. You probably have the best idea how til clean it up?

Thanks for your help.
Best regards
Bård
