### ISSUE TITLE
Degrading responsiveness, runaway memory, and unhandled exceptions

### ISSUE THREAD

**Issue by John867530nine** [cedalo/management-center#55]
Using Windows 10, using container provided here: https://hub.docker.com/r/cedalo/management-center

I have experienced the following over several releases including today's most recent.

The container is configured to run a local mosquitto broker because the container will not run otherwise. It is configured to connect to a remote broker on the internet. Sheets was removed.

```
version: "3.6"
services:
  mosquitto:
    image: eclipse-mosquitto:2-openssl
    ports:
      - 1883:1883
    networks:
      - cedalo-platform
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
  management-center:
    image: cedalo/management-center:2
    ports:
      - 8088:8088
    depends_on:
      - mosquitto
    networks:
      - cedalo-platform
    environment:
      CEDALO_MC_BROKER_ID: mosquitto-2.0
      CEDALO_MC_BROKER_NAME: Mosquitto 2.0
      CEDALO_MC_BROKER_URL: REDACTED
      CEDALO_MC_BROKER_USERNAME: REDACTED
      CEDALO_MC_BROKER_PASSWORD: REDACTED
      CEDALO_MC_USERNAME: cedalo
      CEDALO_MC_PASSWORD: mmcisawesome
networks:
  cedalo-platform:
    name: cedalo-platform
    driver: bridge
```

The basic administrative functions work but the container performance degrades according to the number of clients and ACLs.  I have less than 30 clients configured, each with one ACL. The container is stable through the GUI login process. The problems manifest when attempting anything that queries or adjusts the broker security policy.

With low client count, symptoms were an ever increasing amount of interface lag. Eventually the app began complaining about response timeout though I could see data arriving is less than a second in the container terminal. Currently at around 30 configured clients, the container apparently faults, consuming all available physical memory on the docker host. It will occasionally throw an unhandled exception and die. Most times, I have to kill the container or docker to recover.

Suggestions?
